// Code generated by BobGen sql (devel). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dbinfo

import "github.com/aarondl/opt/null"

var SchemaMigrations = Table[
	schemaMigrationColumns,
	schemaMigrationIndexes,
	schemaMigrationForeignKeys,
	schemaMigrationUniques,
	schemaMigrationChecks,
]{
	Schema: "",
	Name:   "schema_migrations",
	Columns: schemaMigrationColumns{
		Version: column{
			Name:      "version",
			DBType:    "VARCHAR(128)",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
	},
	Indexes: schemaMigrationIndexes{
		SqliteAutoindexSchemaMigrations1: index{
			Type: "pk",
			Name: "sqlite_autoindex_schema_migrations_1",
			Columns: []indexColumn{
				{
					Name:         "version",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:  true,
			Comment: "",
			Partial: false,
		},
	},
	PrimaryKey: &constraint{
		Name:    "pk_main_schema_migrations",
		Columns: []string{"version"},
		Comment: "",
	},

	Comment: "",
}

type schemaMigrationColumns struct {
	Version column
}

func (c schemaMigrationColumns) AsSlice() []column {
	return []column{
		c.Version,
	}
}

type schemaMigrationIndexes struct {
	SqliteAutoindexSchemaMigrations1 index
}

func (i schemaMigrationIndexes) AsSlice() []index {
	return []index{
		i.SqliteAutoindexSchemaMigrations1,
	}
}

type schemaMigrationForeignKeys struct{}

func (f schemaMigrationForeignKeys) AsSlice() []foreignKey {
	return []foreignKey{}
}

type schemaMigrationUniques struct{}

func (u schemaMigrationUniques) AsSlice() []constraint {
	return []constraint{}
}

type schemaMigrationChecks struct{}

func (c schemaMigrationChecks) AsSlice() []check {
	return []check{}
}
