// Code generated by BobGen sql (devel). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"github.com/stephenafamo/bob/clause"
	"github.com/stephenafamo/bob/dialect/sqlite"
	"github.com/stephenafamo/bob/dialect/sqlite/dialect"
)

var (
	SelectWhere     = Where[*dialect.SelectQuery]()
	UpdateWhere     = Where[*dialect.UpdateQuery]()
	DeleteWhere     = Where[*dialect.DeleteQuery]()
	OnConflictWhere = Where[*clause.ConflictClause]() // Used in ON CONFLICT DO UPDATE
)

func Where[Q sqlite.Filterable]() struct {
	Credentials      credentialWhere[Q]
	Files            fileWhere[Q]
	Items            itemWhere[Q]
	SchemaMigrations schemaMigrationWhere[Q]
	Users            userWhere[Q]
} {
	return struct {
		Credentials      credentialWhere[Q]
		Files            fileWhere[Q]
		Items            itemWhere[Q]
		SchemaMigrations schemaMigrationWhere[Q]
		Users            userWhere[Q]
	}{
		Credentials:      buildCredentialWhere[Q](Credentials.Columns),
		Files:            buildFileWhere[Q](Files.Columns),
		Items:            buildItemWhere[Q](Items.Columns),
		SchemaMigrations: buildSchemaMigrationWhere[Q](SchemaMigrations.Columns),
		Users:            buildUserWhere[Q](Users.Columns),
	}
}
