// Code generated by BobGen sql (devel). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models_test

import (
	models "github.com/spotdemo4/ts-server/internal/models"
	"github.com/stephenafamo/bob"
)

// Set the testDB to enable tests that use the database
var testDB bob.Transactor

// Make sure the type Credential runs hooks after queries
var _ bob.HookableType = &models.Credential{}

// Make sure the type File runs hooks after queries
var _ bob.HookableType = &models.File{}

// Make sure the type Item runs hooks after queries
var _ bob.HookableType = &models.Item{}

// Make sure the type SchemaMigration runs hooks after queries
var _ bob.HookableType = &models.SchemaMigration{}

// Make sure the type User runs hooks after queries
var _ bob.HookableType = &models.User{}
