// Code generated by BobGen sql (devel). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import "github.com/stephenafamo/bob"

// Set the testDB to enable tests that use the database
var testDB bob.Transactor

// Make sure the type Credential runs hooks after queries
var _ bob.HookableType = &Credential{}

// Make sure the type File runs hooks after queries
var _ bob.HookableType = &File{}

// Make sure the type Item runs hooks after queries
var _ bob.HookableType = &Item{}

// Make sure the type SchemaMigration runs hooks after queries
var _ bob.HookableType = &SchemaMigration{}

// Make sure the type User runs hooks after queries
var _ bob.HookableType = &User{}
