// Code generated by BobGen sql (devel). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dberrors

var CredentialErrors = &credentialErrors{
	ErrUniquePkMainCredential: &UniqueConstraintError{
		schema:  "",
		table:   "credential",
		columns: []string{"cred_id"},
		s:       "pk_main_credential",
	},
}

type credentialErrors struct {
	ErrUniquePkMainCredential *UniqueConstraintError
}
