name: release

on:
  push:
    tags: ['v*']

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: https://github.com/actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - uses: https://github.com/DeterminateSystems/nix-installer-action@90bb610b90bf290cad97484ba341453bd1cbefea # v19
      - uses: https://github.com/spotdemo4/nix-simple-cache-action@b559f8e40714a57f02221dfe464f780a09df9e0e # v1.5.3

      - run: nix flake check -L --accept-flake-config

  build:
    needs: check
    runs-on: ubuntu-latest
    steps:
      - uses: https://github.com/actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - uses: https://github.com/DeterminateSystems/nix-installer-action@90bb610b90bf290cad97484ba341453bd1cbefea # v19
      - uses: https://github.com/spotdemo4/nix-simple-cache-action@b559f8e40714a57f02221dfe464f780a09df9e0e # v1.5.3

      - run: |
          mkdir binaries

          nix build .#linux-amd64 --accept-flake-config
          tar czf ts-server-linux-amd64.tar.gz -C result/bin ts-server
          mv ts-server-linux-amd64.tar.gz binaries

          nix build .#linux-arm64 --accept-flake-config
          tar czf ts-server-linux-arm64.tar.gz -C result/bin ts-server
          mv ts-server-linux-arm64.tar.gz binaries

          nix build .#linux-arm --accept-flake-config
          tar czf ts-server-linux-arm.tar.gz -C result/bin ts-server
          mv ts-server-linux-arm.tar.gz binaries

          nix build .#darwin-arm64 --accept-flake-config
          tar czf ts-server-darwin-arm64.tar.gz -C result/bin ts-server
          mv ts-server-darwin-arm64.tar.gz binaries

          nix build .#windows-amd64 --accept-flake-config
          zip -j ts-server-windows-amd64.zip result/bin/ts-server.exe
          mv ts-server-windows-amd64.zip binaries

      - uses: https://gitea.com/actions/gitea-release-action@fe8e0322804b48e34e3bddbbf6335bd2b1046eb7 # v1
        with:
          files: |-
            binaries/*

  package:
    needs: check
    runs-on: ubuntu-latest
    steps:
      - uses: https://github.com/actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - uses: https://github.com/DeterminateSystems/nix-installer-action@90bb610b90bf290cad97484ba341453bd1cbefea # v19
      - uses: https://github.com/spotdemo4/nix-simple-cache-action@b559f8e40714a57f02221dfe464f780a09df9e0e # v1.5.3

      - uses: https://github.com/nicknovitski/nix-develop@9be7cfb4b10451d3390a75dc18ad0465bed4932a # v1.2.1
        with:
          arguments: '--accept-flake-config'

      - name: Build & push images
        run: |
          nix build .#image --accept-flake-config

          TAG=${{ github.ref_name }}
          VERSION=${TAG#v}

          ./result | gzip --fast | skopeo copy \
            --dest-creds=${{ github.actor }}:${{ secrets.GITHUB_TOKEN }} \
            docker-archive:/dev/stdin \
            docker://gitea.com/spotdemo4/ts-server:$VERSION

  tag:
    needs: check
    runs-on: ubuntu-latest
    steps:
      - uses: https://github.com/actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - run: git push origin "${{ github.ref_name }}:latest" --force
