// Code generated by BobGen sql (devel). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dberrors

var FileErrors = &fileErrors{
	ErrUniquePkMainFile: &UniqueConstraintError{
		schema:  "",
		table:   "file",
		columns: []string{"id"},
		s:       "pk_main_file",
	},
}

type fileErrors struct {
	ErrUniquePkMainFile *UniqueConstraintError
}
