// Code generated by BobGen sql (devel). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dberrors

var ItemErrors = &itemErrors{
	ErrUniquePkMainItem: &UniqueConstraintError{
		schema:  "",
		table:   "item",
		columns: []string{"id"},
		s:       "pk_main_item",
	},
}

type itemErrors struct {
	ErrUniquePkMainItem *UniqueConstraintError
}
