// Code generated by BobGen sql (devel). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dberrors

var SchemaMigrationErrors = &schemaMigrationErrors{
	ErrUniquePkMainSchemaMigrations: &UniqueConstraintError{
		schema:  "",
		table:   "schema_migrations",
		columns: []string{"version"},
		s:       "pk_main_schema_migrations",
	},
}

type schemaMigrationErrors struct {
	ErrUniquePkMainSchemaMigrations *UniqueConstraintError
}
