// Code generated by BobGen sql (devel). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dberrors

var UserErrors = &userErrors{
	ErrUniquePkMainUser: &UniqueConstraintError{
		schema:  "",
		table:   "user",
		columns: []string{"id"},
		s:       "pk_main_user",
	},
}

type userErrors struct {
	ErrUniquePkMainUser *UniqueConstraintError
}
