// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"time"
)

type Credential struct {
	CredID                string
	CredPublicKey         []byte
	SignCount             int64
	Transports            *string
	UserVerified          *bool
	BackupEligible        *bool
	BackupState           *bool
	AttestationObject     []byte
	AttestationClientData []byte
	CreatedAt             time.Time
	LastUsed              time.Time
	UserID                int64
}

type File struct {
	ID     int64
	Name   string
	Data   []byte
	UserID int64
}

type Item struct {
	ID          int64
	Name        string
	Added       time.Time
	Description string
	Price       float64
	Quantity    int64
	UserID      int64
}

type SchemaMigration struct {
	Version string
}

type User struct {
	ID               int64
	Username         string
	Password         string
	ProfilePictureID *int64
	WebauthnID       string
}
