#!/usr/bin/env bash

git fetch
git_root=$(git rev-parse --show-toplevel)
updated=false

echo "updating nix flake"
cd "${git_root}"
nix flake update
if ! git diff --exit-code flake.lock; then
    git add flake.lock
    git commit -m "build(nix): updated nix dependencies"
fi

echo "updating proto submodule"
cd "${git_root}"
git submodule update --rebase --remote
if ! git diff --exit-code proto; then
    git add proto
    git commit -m "build(proto): updated protobuf files"
    echo "you need to buf generate!"
fi

echo "updating go"
cd "${git_root}"
go get -u
go mod tidy
if ! git diff --exit-code go.mod go.sum; then
    git add go.mod
    git add go.sum
    git commit -m "build(server): updated go dependencies"
    updated=true
fi

if [ "${updated}" = true ]; then
    echo "updating nix hashes"
    cd "${git_root}"
    nix-update --flake --version=skip default
    git add flake.nix
    git commit -m "build(nix): updated nix hashes"
fi