name: renovate

on:
  schedule:
    - cron: "0/15 * * * *"

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v42
        with:
          configurationFile: .github/renovate.json
          token: ${{ secrets.PAT }}
