name: renovate

on:
  schedule:
    - cron: "0 0 * * *"
    - cron: "30 0 * * *"
  workflow_dispatch:

jobs:
  runner:
    runs-on: ubuntu-latest
    outputs:
      label: ${{ steps.runner.outputs.label }}
    steps:
      - name: Get runner
        id: runner
        run: |
          runners=$(curl -s -H "Accept: application/vnd.github+json" -H "Authorization: token ${{ secrets.PAT }}" "https://api.github.com/repos/${{ github.repository }}/actions/runners")
          available=$(echo "$runners" | jq '.runners[] | select(.status == "online" and .labels[] .name == "self-hosted")')
          if [ -n "$available" ]; then
            echo "label=self-hosted" >> $GITHUB_OUTPUT
          else
            echo "label=ubuntu-latest" >> $GITHUB_OUTPUT
          fi

  renovate:
    needs: runner
    runs-on: ${{ needs.runner.outputs.label }}
    steps:
      - uses: actions/checkout@v4

      - uses: DeterminateSystems/nix-installer-action@main

      - uses: DeterminateSystems/magic-nix-cache-action@main

      - uses: nicknovitski/nix-develop@v1
        with:
          arguments: ".#ci"

      - uses: actions/create-github-app-token@v2
        id: token
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}

      - name: Renovate
        env:
          RENOVATE_CONFIG_FILE: .github/renovate-global.json
          RENOVATE_TOKEN: ${{ steps.token.outputs.token }}
          RENOVATE_GITHUB_COM_TOKEN: ${{ secrets.PAT }}
          LOG_LEVEL: debug
        run: renovate
